spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test/awesome/awesome
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-exception: true
    include-message: always

file:
  dir: ${user.home}/test/awesome/awesome_file_dir/

logging.level:
  org.hibernate.SQL: debug